name: Deploy Next.js App to GitHub Pages

on:
  push:
    branches:
      - main  # Change this to your default branch
  schedule:
    - cron: '0 */6 * * *'  # Run every 6 hours

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.10.0'  # Ensure this matches your Node version

    - name: Install dependencies
      run: npm install --force


    - name: Build and export Next.js app
      run: npm run dev

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./out
        cname: C0oki3s.xyz  # Add your custom domain here if applicable
